(deftheme custom1
  "Created 2017-08-29.")

(custom-theme-set-faces
 'custom1
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:background "#1c1c1c" :foreground "#005f5f" :box (:line-width -1 :color "red" :style released-button) :weight bold))))
 '(highlight ((t (:weight ultra-bold))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((t (:background "#5f0000"))))
 '(font-lock-builtin-face ((t (:foreground "color-75"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:foreground "#585858" :weight semi-bold))))
 '(font-lock-constant-face ((t (:foreground "#8700d7"))))
 '(font-lock-doc-face ((t (:foreground "indian red"))))
 '(font-lock-function-name-face ((t (:foreground "#005fff"))))
 '(font-lock-keyword-face ((t (:foreground "cyan" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#0087ff"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#00d700"))))
 '(font-lock-type-face ((t (:foreground "#008700" :weight semi-bold))))
 '(font-lock-variable-name-face ((t (:foreground "#ffd700"))))
 '(font-lock-warning-face ((t (:foreground "#af0000" :weight bold))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#0066CC"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#6799CC"))))
 '(fringe ((t (:background "#E6E6E6"))))
 '(header-line ((t (:box (:line-width -1 :color "red" :style released-button) :inverse-video t :foreground "#CCCCCC" :background "black"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "#303030" :foreground "#2E3436" :box (:line-width 1 :color "red") :family "DejaVu Sans"))))
 '(mode-line-inactive ((t (:background "#121212" :foreground "#303030" :box (:line-width 1 :color "red") :family "DejaVu Sans"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
 '(my-tab-face ((t (:foreground "#444444" :underline t :weight extra-bold))))
 '(error ((t (:foreground "#ff87d7" :weight bold))))
 '(warning ((default (:weight bold)) (((class color) (min-colors 16)) (:foreground "DarkOrange")) (((class color)) (:foreground "yellow"))))
 '(success ((default (:weight bold)) (((class color) (min-colors 16) (background light)) (:foreground "ForestGreen")) (((class color) (min-colors 88) (background dark)) (:foreground "Green1")) (((class color) (min-colors 16) (background dark)) (:foreground "Green")) (((class color)) (:foreground "green"))))
 '(region ((t (:background "color-239")))))

(provide-theme 'custom1)
